spring.application.name=ORYX

# ===============================
# SERVER
# ===============================
server.port=8888
server.servlet.context-path=/

# ===============================
# DATASOURCE
# ===============================
#spring.datasource.url=jdbc:mysql://localhost:3306/oryx?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/oryx
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# HIKARI CONNECTION POOL
# ===============================
spring.datasource.hikari.pool-name=OryxHikariPool
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.leak-detection-threshold=60000

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.file.name=logs/app.log

# Optional log pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# ===============================
# JWT
# ===============================
ORYX.app.jwtSecret=${JWT_SECRET:TXlTdXBlclNlY3JldEtleTEyMzQ1Njc4OTAxMjM0NTY=}
ORYX.app.jwtExpirationMs=86400000

# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# ===============================
# JACKSON
# ===============================
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.jackson.time-zone=Africa/Cairo

# ===============================
# ACTUATOR (Optional but Recommended)
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always